### ISSUE TITLE
Possible to support BungeeCord

### ISSUE THREAD

**Issue by smallshen** [DevSrSouza/KotlinBukkitAPI#10]
Is that Possible to have a BungeeCord Support
That would be useful too.

Also please have documents on exposed cause that is a bit complex

**Comment by DevSrSouza** [comment]
Port the KotlinBukkkitAPI to BungeeCord is kinda so much work to do and I don't have much time to spend at my side projects like KotlinBukkitAPI currently.

This is an idea that I was thinking in the last year but because of the time, I'm not able to work on it.

About the Exposed documentation, I will do that soon.

**Comment by DevSrSouza** [comment]
Exposed documentation is done!

https://github.com/DevSrSouza/KotlinBukkitAPI/wiki/Exposed
