### ISSUE TITLE
Expose vendor as separate plugin too

### ISSUE THREAD

**Issue by stevefan1999-personal** [DevSrSouza/KotlinBukkitAPI#12]
Hi, I also package my own Kotlin runtime (in fact an entire classpath plugin to store all vendor code) and there's some kind of discrepancy with my Coroutine too. I used a newer version of Kotlinx.coroutine and I saw an error on the console `[02:36:10 WARN]: [stevefan1999-proto] Loaded class kotlin.coroutines.Continuation from KotlinBukkitAPI v0.1.0-SNAPSHOT which is not a depend, softdepend or loadbefore of this plugin.` which means we are mixing class loaders. 

This is not good as it means some vague error such as apparent-from-same-package-but-actually-cross-class-loader thingy will occur. So I suggest isolating all vendor code (e.g. Kotlin, Kotlinx, Exposed) also into a depend/softdepend?

**Comment by DevSrSouza** [comment]
Hi @stevefan1999-personal, when using KotlinBukkitAPI you should let him take care of this libraries, if is a old version that it is using, create an issue and I will update it (if I forgot) or send a PR.

KotlinBukkitAPI don't change the Kotlin, Coroutines and Serialization (that is the libraries shipped into it) package names (remapping) because when you will use at your project, will no match with the KotlinBukkitAPI packages, and this could be a problem.

If your plugin is using KotlinBukkitAP, it should `depend` on KotlinBukkitAPI plugin at the `plugin.yml`.

I truly don't know how to fix this cases, I think an easy to fix is not shade the Kotlin and Coroutines into your plugin and let it to KotlinBukkitAPI.

If it does not use KotlinBukkitAPI, you should use Shadow plugin and remap Kotlin and Coroutines packages for only your plugin.

I don't know how isolating all vendor could fix it, maybe you can explain it more to me?

**Comment by DevSrSouza** [comment]
Thinking better now, if I understand correctly, you want to me create a plugin just for the Kotlin stuffs, like Kotlin STD and Coroutines?

**Comment by stevefan1999-personal** [comment]
@DevSrSouza yeah, and then your own Kotlin code will reference your newly created vendor plugin too, and maybe someday people will also use that vendor plugin.

**Comment by DevSrSouza** [comment]
I don't know if this is a good approach for what I want the library to be.

The focus of KotlinBukkitAPI is to be the center for Plugin using Kotlin because it allows to you don't require to ship the Kotlin STD, Coroutines and Serialization into your plugin make it small in jar size.

If I update the shipped Coroutines will help you to not shadow into your plugin?

**Comment by stevefan1999-personal** [comment]
@DevSrSouza Well only if you can keep up with the changes Jetbrains did to Kotlin. I suggest using Dependabot for automatically upgrading your dependencies and also automatically upload a new version.

**Comment by stevefan1999-personal** [comment]
Or better yet since you are self hosting you can try https://github.com/renovatebot/renovate which has a self host option, but you will need a cronjob to do repo scanning like every half a day

**Comment by DevSrSouza** [comment]
The reason that I don't think that create a separated vendor plugin is good thing because in the future, other projects could be running KotlinBukkitAPI and someone could have two plugins that use the API and do not use the Vendor plugin approach, shipping Kotlin STD and Coroutines into it causing the same issue.

The main difference from this is that KBAPI is open source, maybe the plugin that this folk could be using private source, and he can't fix it.

I will work on add Dependabot and Github Actions to the project.
Tkx alot, this is really important for the project, I this is a issue that can happen with anyone and I will put it on the documentation.
